default:
  image: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

workflow:
  rules:
    # Do not duplicate commit and merge request pipelines
    # See https://docs.gitlab.com/ci/yaml/workflow/#switch-between-branch-pipelines-and-merge-request-pipelines
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

build:
  stage: build
  # See https://docs.gitlab.com/ci/docker/using_docker_build/#use-docker-in-docker
  image: docker:29.4.0
  services:
    - docker:29.4.0-dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build --network=host
                   --push
                   --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
                   --target latest ./

pytest:
  script:
    - ./run.sh test

precommit:
  script:
    - pre-commit run

precommitall:
  script:
    - pre-commit run --all
  allow_failure: true

rstest:
  script:
    - cargo test
