default:
  image: $CI_REGISTRY_IMAGE:latest

workflow:
  rules:
    # Do not duplicate commit and merge request pipelines
    # See https://docs.gitlab.com/ci/yaml/workflow/#switch-between-branch-pipelines-and-merge-request-pipelines
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

pytest:
  script:
    - pytest

precommit:
  script:
    - pre-commit run

precommitall:
  script:
    - pre-commit run --all
  allow_failure: true

rstest:
  script:
    - cargo test
