repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: no-commit-to-branch
    -   id: pretty-format-json
        args: [--autofix]
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: https://github.com/doublify/pre-commit-rust.git
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
